In [1]:
import numpy as np

In [2]:
# Crearemos una matrz de 3 * 4
matriz = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [3]:
# Para seleccionar la fila 2 que es la 1
matriz[1]

array([5, 6, 7, 8])

In [4]:
# Para seleccionar hasta la fila 2 (Aquí no se le resta 1)
matriz[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# Para seleccionar la columna 3 que es la 2
matriz[:,2]

array([ 3,  7, 11])

In [6]:
# Para seleccionar un elemento por ejemplo el que tiene valor 6
matriz[1,1]

6

In [7]:
# Una nota con las seleccion y la seccion
# Vamos a seleccionar un elemento de la matriz
seleccion = matriz[2,3]
seleccion


12

In [8]:
#Cuando seleccionamos un atributo de una matriz nos devuelve una copia del elemento de la matriz
# Con loq que si lo ponemos en una variable podemos cambiar el valor de la avriable sin afectar a la matriz
seleccion = 123456
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# Pero si hacemos una selección de una sección de una matriz
# Nos devuelve la parte seleccionada de la matriz original
seccion = matriz[:2]
seccion

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# Con lo que si modificamos un valor dentro de la variable de sección
# Afectamos a la amtriz original
seccion[1,1] = 123456
matriz

array([[     1,      2,      3,      4],
       [     5, 123456,      7,      8],
       [     9,     10,     11,     12]])

In [11]:
# Vamos a crear una matriz de 3 * 2
matriz_32 = np.array([
    [0, 3],
    [2, 3],
    [5, 2]
])
matriz_32

array([[0, 3],
       [2, 3],
       [5, 2]])

In [12]:
# Ahora crearemos un filtro para la matriz
indices_filtrados = matriz_32 >= 3
indices_filtrados

array([[False,  True],
       [False,  True],
       [ True, False]])

In [13]:
# Ahora para obtener los valores de la matriz que cumplan con esa condicion
matriz_32[indices_filtrados]

array([3, 3, 5])

In [14]:
# Ahora crearemos 2 arrays
array1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array1 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array2 = np.array([
    [10,11,12],
    [13,14,15],
    [16,17,18]
])

array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [16]:
# Para hacer operaciones sencillas por ejemplo suma
array1 + array2

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [17]:
# Ahora una division
array1 / array2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [18]:
# Ahora para hacer una multiplicacion de matriz array1 • array2
array1 @ array2

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [19]:
# Para hacer lo mismo array1 • array2 en versiones viejas de python
array1.dot(array2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])